server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enbale: true

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: feign-consumer

